---
mysql:
  image: mysql:5.7
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  persistence:
    storage: 8Gi

  replication:
    user: ''
    password: ''
    # user: 'random_string'
    # password: 'random_string123'


tools:
  image: gcr.io/pl-infra/titanium-toolbox:latest
  resources:
    # backup server resources
    requests:
      cpu: 100m
      memory: 100Mi


gsCredentialsFile:

initBucketURI:
backupBucket:

scheduleBackup: "0 * * * *"

persistenceDisabled: false
