pipeline:
  build:
    image: plugins/docker
    mirror: https://mirror.gcr.io
    registry: gcr.io
    repo: gcr.io/pl-infra/titanium-toolbox
    username: _json_key
    tags: ["${DRONE_BRANCH/master/latest}", "${DRONE_COMMIT_SHA:0:7}"]
    force_tag: true
    build_args:
      - release="${DRONE_COMMIT_SHA:0:7}"
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: DOCKER_PASSWORD
    when:
      event: push

  test:
    image: gcr.io/pl-infra/kluster-toolbox:latest
    pull: true
    secrets:
      - GOOGLE_CREDENTIALS
    environment:
      - TITANIUM_IMAGE_TAG="${DRONE_COMMIT_SHA:0:7}"
      - PLUGIN_PROJECT=staging-reactor
      - PLUGIN_ZONE=us-east1-b
      - PLUGIN_CLUSTER=test
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - pip3 install -r requirements.dev.txt
      - python3 -m pytest -v --capture=no
