apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy: sha256
  artifacts:
  - imageName: mysql-helper
    workspace: hack/docker/mysql-helper
  - imageName: mysql-operator
    workspace: hack/docker/mysql-operator
  local:
    skipPush: true
deploy:
  helm:
    releases:
    - name: test
      chartPath: hack/charts/controller
      values:
        image: mysql-operator
        conf.helper-image: mysql-helper
