apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy: sha256
  artifacts:
  - imageName: titanium-toolbox
    dockerfilePath: hack/docker/toolbox/Dockerfile
    workspace: .
  - imageName: titanium-controller
    dockerfilePath: Dockerfile
    workspace: .
  local:
    skipPush: true
deploy:
  helm:
    releases:
    - name: test
      chartPath: hack/charts/controller
      values:
        image: titanium-controller
        conf.titanium-toolbox-image: titanium-toolbox
