apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  credentials.json: {{ toString .Values.gsCredentialsFile | b64enc | quote }}
  TITANIUM_REPLICATION_USER: {{ default .Values.mysql.replication.user (randAlpha 6) | b64enc | quote }}
  TITANIUM_REPLICATION_PASSWORD: {{ default .Values.mysql.replication.password (randAlphaNum 16) | b64enc | quote }}
