{{- if and .Values.scheduleBackup .Values.backupBucket }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.scheduleBackup }}

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: config-map
              configMap:
                name: {{ .Release.Name }}-mysql
            - name: secret-conf
              secret:
                secretName: {{ .Release.Name }}-mysql-secrets

          containers:
            - name: backup
              image: {{ .Values.tools.image }}
              command: [ "db", "backup" ]
              env:
              {{- include "titanium.env" . | nindent 14 }}

              volumeMounts:
              - name: secret-conf
                mountPath: /var/run/secrets/
              - name: config-map
                mountPath: /mnt/config-map
{{- end }}
