{{- if .Values.db.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  DB_CONNECT_URL: {{ include "db-connect-url" . | b64enc | quote }}
  DB_HOST: {{ include "dbHost" . | b64enc | quote }}
  DB_NAME: {{ include "dbName" . | b64enc | quote }}
  DB_PASSWORD: {{ include "dbPassword" . | b64enc | quote}}
  DB_PORT: {{ include "dbPort" . | b64enc | quote }}
  DB_USER: {{ include "dbUser" . | b64enc | quote }}
  
{{- end }}
