---
mysql:
  image: percona:5.7
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 1Gi

  persistence:
    storage: 8Gi

  replication:
    user: ''
    password: ''

  allowEmptyPassword: false
  rootPassword: ''

db:
  name: ''
  user: ''
  password: ''


tools:
  image: gcr.io/pl-infra/titanium-toolbox:latest
  resources:
    # backup server resources
    requests:
      cpu: 100m
      memory: 100Mi


gsCredentialsFile:

initBucketURI:
backupBucket:

scheduleBackup: "0 * * * *"

persistenceDisabled: false
