---
mysql:
  image: percona:5.7
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 1Gi

  persistence:
    storage: 8Gi

  replicationUser: ''
  replicationPassword: ''

  allowEmptyPassword: false
  rootPassword: ''

  dbName: ''
  dbUser: ''
  dbPassword: ''

mysqlConfig:
  character-set-server: utf8mb4
  collation-server: utf8mb4_unicode_ci

  # MyISAM #
  key-buffer-size: 32M
  myisam-recover-options: "FORCE,BACKUP"

  # SAFETY #
  max-allowed-packet: 16M
  max-connect-errors: "1000000"
  skip-name-resolve: "ON"
  sql-mode:
    "STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,\
    NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,\
    NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY"
  sysdate-is-now: 1

  # BINARY LOGGING #
  expire-logs-days: 5
  sync-binlog: 1
  binlog-format: ROW

  # CACHES AND LIMITS #
  tmp-table-size: 32M
  max-heap-table-size: 32M
  query-cache-type: 0
  query-cache-size: 0
  max-connections: 500
  thread-cache-size: 50
  open-files-limit: 65535
  table-definition-cache: 4096
  table-open-cache: 4096

  # INNODB #
  innodb-flush-method: O_DIRECT
  innodb-log-files-in-group: 2
  innodb-log-file-size: 128M
  innodb-flush-log-at-trx-commit: 2
  innodb-file-per-table: 1
  # innodb-buffer-pool-size: 800M  # setted for 80% from RAM

  # LOGGING #
  log-queries-not-using-indexes: 1
  slow-query-log: 1


tools:
  image: gcr.io/pl-infra/titanium-toolbox:latest
  resources:
    # backup server resources
    requests:
      cpu: 100m
      memory: 100Mi


gsCredentialsFile:

initBucketURI:
backupBucket:
backupPredix: 

scheduleBackup: "0 0 * * *"

persistenceDisabled: false
