apiVersion: titanium.presslabs.net/v1alpha1
kind: MysqlBackup
metadata:
  name: bar-backup

spec:
  clusterName: foo
  bucketUri: gs:pl-test-mysql-backups/ti/bar-backup.xtrabackup.gz
  bucketSecretName: backup-secret
