apiVersion: titanium.presslabs.net/v1alpha1
kind: MysqlBackup
metadata:
  name: bar-backup

spec:
  clusterName: foo
  bucketUri: gs:pl-test-mysql-backups/ti/bar-backup.xtrabackup.gz
  # TODO maybe implement this
  # if bucketUri is not specified then cluster.backupBucketUri + bucketSuffix + .xtrabackup.gz is used
  # else a random suffix is used
  # bucketSuffix: this-is-my-backup
  bucketSecretName: backup-secret
